### ISSUE TITLE
`'NoneType' object has no attribute 'name'` when upgrading from 3.1.1 to 5.x

### ISSUE THREAD

**Issue by jasperbok** [django-cms/djangocms-snippet#187]
I upgraded `djangocms-snippet` from `3.1.1` to `5.0.1` in a Django CMS 3.11 project, and am now unable to add snippets from the structure editor.

When trying to add a snippet plugin, the admin popup opens showing the error `'NoneType' object has no attribute 'name'`. The error is triggered in `djangocms_snippet/models.py, line 39`, in the `SnippetGrouper` class.

My installed versions are:

- `django==4.2.23`
- `django-cms==3.11.10`
- `djangocms-snippet==5.0.1`

**Comment by ms-18** [comment]
I can reproduce the error!
With
`django==4.2.18`
`django-cms==3.11.9`
`djangocms-snippet==5.0.0`
so no versioning.
When I delete a Snippet, the SnippetGrouper doesn't get deleted. When the choice widget is rendered for the create/change form of the SnippetPlugin it tries to str() all possible SnippetGrouper instances which in turn tries to access their linked snippets to get a name.

```python
def __str__(self):
    return self.name

@property
def name(self):
    snippet_qs = Snippet.admin_manager.filter(snippet_grouper=self)
    return snippet_qs.first().name or super().__str__
```
in [models.py](https://github.com/django-cms/djangocms-snippet/blob/5.0.1/src/djangocms_snippet/models.py#L36)

Would it be enough to override the delete method to check if the linked SnippetGroup is referenced by other Snippet instances and if not also delete it? I could make a pull request with this change tomorrow.

Of course there might be other data migration issues but I didn't investigate this any further as I stumbled across this problem in the scenario mentioned above.
